### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by qinix** [qinix/shelter#5]
## Version 0.1.0

- [x] 实现用户登录注册

- [x] 实现用户可以在自己的个人账户下创建仓库

- [x] 实现用户可以给自己账户下的仓库 push/pull

## Version 0.2.0

- [x] 实现 Internationalization

- [x] 实现用户 A 可以查看和 pull 用户 B 的 public 仓库

- [x] 实现搜索

- [x] 实现仓库 Description 使用 markdown 语法渲染

- [x] 实现 Project member, 成员拥有对仓库的写权限

- [x] 初步实现 Organization

    - [x] 实现用户可以创建 Organization

    - [x] 实现用户可以创建 Organization 下的仓库

    - [x] 实现 Organization member，Organization 中的成员拥有对组织中所有的仓库的写权限

    - [x] Organization 中的 public 仓库可以对所有人显示

## Version 0.2.1

- [x] 完善首页及部分跳转细节

- [x] 完整的测试鉴权机制是否有遗漏

## Version 0.3.0

- [x] 实现管理员管理

    - [x] 新增、搜索、删除用户

    - [x] 修改注册模式
